// Generated by Flux Compiler
#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(unused_imports)]

use fluno::prelude::*;

fn main() {
    println("Testing Gaussian Sampling...".to_string());
    let mut g = Gaussian(0.0, 1.0);
    let mut x = sample(g.clone());
    println("Sampled value:".to_string());
    println(x);
    let mut g2 = Gaussian(10.0, 2.0);
    let mut g3 = (g + g2);
    println("Combined Gaussian:".to_string());
    let mut y = sample(g3);
    println(y)
}

