// Generated by Flux Compiler
#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(unused_imports)]

use fluno::prelude::*;

#[derive(Debug, Clone)]
pub struct Point {
    pub x: i64,
    pub y: i64,
}

fn main() {
    let mut p = Point { x: 10, y: 20 };
    println(p.x);
    match p {
        Point { x, y } =>         {
            println(x);
            println(y)
        }
,
    };
    match p {
        Point { x: 10, y } =>         {
            println("Matched x=10".to_string())
        }
,
        _ =>         {
            println("Not matched".to_string())
        }
,
    }
}

