// Generated by Flux Compiler
#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(unused_imports)]

use fluno::prelude::*;

pub trait Drawable {
    fn draw(&self);
}

#[derive(Debug, Clone)]
pub struct Circle {
    pub radius: i64,
}

impl Drawable for Circle {
    fn draw(&self) -> ()     {
        println("Drawing Circle with radius:".to_string());
        println(self.radius)
    }


}

fn main() {
    let mut c = Circle { radius: 10 };
    c.draw()
}

