// Generated by Flux Compiler
#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(unused_imports)]

use fluno::prelude::*;

#[derive(Debug, Clone)]
pub enum Color {
    Red,
    Green,
    Blue,
    RGB(i64, i64, i64),
}

fn main() {
    println("Testing Enums...".to_string());
    let mut c = Color::Red;
    match c {
        Color::Red => println("It is Red!".to_string()),
        Color::Green => println("It is Green!".to_string()),
        _ => println("Other color".to_string()),
    };
    let mut rgb = Color::RGB(100, 200, 50);
    match rgb {
        Color::RGB(r, g, b) =>         {
            println("RGB Color:".to_string());
            println(r.to_string());
            println(g.to_string());
            println(b.to_string())
        }
,
        _ => println("Not RGB".to_string()),
    }
}

