// Generated by Flux Compiler
#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(unused_imports)]

use fluno::prelude::*;

async fn fetch_data() -> ADFloat {
    return ADFloat::from(42.0);
}

#[tokio::main]
async fn main() {
    let mut val = fetch_data().await;
    println(val)
}

