// Generated by Flux Compiler
#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(unused_imports)]

use fluno::prelude::*;

fn identity(x: T) -> T {
    return x.clone();
}

fn wrapper(a: A, b: B) -> A {
    return a.clone();
}

#[tokio::main]
async fn main() {
    let mut x: i64 = identity(10);
    let mut y: ADFloat = identity(ADFloat::from(3.14));
    let mut z = wrapper(x, y);
}

