// Generated by Flux Compiler
#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(unused_imports)]

use fluno::prelude::*;

fn model() -> ADFloat {
    let mut mean = ADFloat::from(5.0);
    let mut std = ADFloat::from(2.0);
    let mut x = sample(Gaussian(mean, std));
    observe(Gaussian(ADFloat::from(10.0), ADFloat::from(1.0)), x);
    x
}

fn main() {
    let mut config = Map();
    let mut samples = infer_hmc(config, model);
    println("Native HMC Samples collected:".to_string());
    println(samples.len())
}

