// Generated by Flux Compiler
#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(unused_imports)]

use fluno::prelude::*;

fn model() -> ADFloat {
    let mut x1 = ADFloat::from(1.0);
    let mut y1 = ADFloat::from(3.0);
    let mut x2 = ADFloat::from(2.0);
    let mut y2 = ADFloat::from(5.0);
    let mut x3 = ADFloat::from(3.0);
    let mut y3 = ADFloat::from(7.0);
    let mut x4 = ADFloat::from(4.0);
    let mut y4 = ADFloat::from(9.0);
    let mut x5 = ADFloat::from(5.0);
    let mut y5 = ADFloat::from(11.0);
    let mut w = sample(Gaussian(ADFloat::from(0.0), ADFloat::from(10.0)));
    let mut b = sample(Gaussian(ADFloat::from(0.0), ADFloat::from(10.0)));
    observe(Gaussian(((w * x1) + b), ADFloat::from(1.0)), y1);
    observe(Gaussian(((w * x2) + b), ADFloat::from(1.0)), y2);
    observe(Gaussian(((w * x3) + b), ADFloat::from(1.0)), y3);
    observe(Gaussian(((w * x4) + b), ADFloat::from(1.0)), y4);
    observe(Gaussian(((w * x5) + b), ADFloat::from(1.0)), y5);
    w
}

fn sum_recursive(samples: Vec<ADFloat>, i: i64, n: i64, acc: ADFloat) -> ADFloat {
    if (i >= n)     {
        acc
    }
 else     {
        let mut val = samples[(i) as usize];
        sum_recursive(samples, (i + 1), n, (acc + val))
    }

}

fn main() {
    println("Running Bayesian Linear Regression (Native)...".to_string());
    let mut config = Map();
    config.insert("iters".to_string(), 1000);
    let mut samples = infer_hmc(config, model);
    let mut N = samples.len();
    println("Samples collected:".to_string());
    println(N);
    let mut total = sum_recursive(samples, 0, N, ADFloat::from(0.0));
    let mut mean = (total / N);
    println("Posterior Mean w:".to_string());
    println(mean)
}

